### ISSUE TITLE
Does nothing

### ISSUE THREAD

**Issue by stefan131** [bsegraves/custom-folds#1]
Hi, 

It's just not working, 
the only thing it does is adding a menu for the addon, that's it.
Would love to use it so please fix it ^^

**Comment by stefan131** [comment]
Hi, 

I was trying to use this on my CSS and HTML

**Comment by bsegraves** [comment]
I think maybe you think the plugin is smarter than it actually is.

From the readme:

> By default, the text `// <editor-fold` identifies the start of a foldable region and `// </editor-fold>` marks the end of the region.

Basically, the plugin allows you to define a custom, foldable tag. By default, the start of a foldable region is identified by the string `// <editor-fold` and the end of a foldable region is identified by `// </editor-fold>`. Unless you manually add these specific tags to your source file, it won't know how to do the folding.

A line starting with `// <editor-fold` isn't valid html. You should be able to change the settings to have it instead be `<!-- editor-fold` and that should work, but then it would only work in your html files.

It's a pretty basic package and in its current form is really only designed to work with one style of code file.

**Comment by stefan131** [comment]
I see it works now, I used `// <editor-fold>` and '// </editor-fold>'
Instead of `// <editor-fold` and '// </editor-fold>'

But there's no fold icon in the sidebar, as there is if I do something like this
`.jumbotron {
   code
}`

**Comment by stefan131** [comment]
Atom has a function built in that does the same btw, see [https://atom.io/docs/v0.194.0/using-atom-folding](url)

**Comment by bsegraves** [comment]
Right, atom has rich, built-in support for code folding. This just adds the ability for you to add additional foldable regions outside the language specification. One example might be creating two regions - one for your class's public api and one for your class's private/internal api.

**Comment by stefan131** [comment]
Atom itself also has the ability to fold code outsife the language specification :p
Read the website.
But, it shouldn't be that hard to add support for the collapse triangle at the sidebar and multiple tags, right?
If you do that, this plugin would be a must have that everyone will be using

---- bsegraves schreef ----

**Comment by bsegraves** [comment]
I think I see what you're saying. When a custom region isn't collapsed, there's no visual indicator in the sidebar like there is for the built-in foldable region. That would be nice - I'll take a look to see if that's easy to add or not (it may not be easy - depends on what the atom api exposes).

As for multiple foldable regions - I agree, that would be nice. That should be much easier to add.

**Comment by thtliife** [comment]
Hi @bsegraves 
Adding the foldable marker is very easy... actually making it work correctly on the other hand, appears to be very difficult....

I'm currently working on a fork which i am trying to implement the fold markers in....
The changes in pull request [#10861](https://github.com/atom/atom/commit/3d953632e64c38c8b050a00009e378a608908017) look quite promising, but would not be suitable for use until v1.7 is marked as the stable release of atom i think....

**Comment by bsegraves** [comment]
Yeah, I looked at it briefly and it didn't seem trivial. I'm currently buried at work. Maybe I'll be able to poke my head up once 1.7 comes out.

If you're able to get anything working definitely submit a PR. Otherwise I'll investigate against with 1.7.

**Comment by bsegraves** [comment]
Closing this as the foldable regions is captured in a different issue.
