### ISSUE TITLE
Does not highlight on start

### ISSUE THREAD

**Issue by 0tho** [bsegraves/custom-folds#10]
When I open atom my files are not highlighted. I have to edit some text so the markers get highlighted.

I tried to debug the problem and found out that on start, [this](https://github.com/bsegraves/custom-folds/blob/master/lib/index.js#L259 ) line returns just ''
Not sure how to fix

**Comment by bsegraves** [comment]
I've seen this occur on large files as well but never on small files, which leads me to believe it's a timing issue.

I've tried looking for an event to listen to, like "document fully loaded", but didn't have much luck in the past. I'll try again now that I'm not the only one seeing this issue.

**Comment by bsegraves** [comment]
Never could find an event in the atom api for this. The only fix I could think of, which is amazingly hacky, is to wait for two animation frames before applying the regions.

I pushed this fix with version 1.8.1.
