### ISSUE TITLE
Turning off highlighting turns off all functionality

### ISSUE THREAD

**Issue by sschwaner** [bsegraves/custom-folds#19]
After unchecking "Enable region highlighting?", I can no longer define foldable regions.  The regions are defined correctly when this option is checked, and as soon as I uncheck it, the regions are no longer permanently defined.

**Comment by bsegraves** [comment]
If I disable region highlighting, I do notice that the downward arrow in the gutter no longer appears.

All the functions still work, however. For example, <ctr><shift>-\ still toggles the foldable region.

I'll take a look at this tonight and try and fix the gutter icon when region highlighting is disabled.

**Comment by bsegraves** [comment]
Thanks for catching this. Gutter icons now work in version 1.9.1, so if you update your custom-folds package it should work for you. If you continue to have problems let me know.
