### ISSUE TITLE
Unfolding current level

### ISSUE THREAD

**Issue by 19Nils92** [bsegraves/custom-folds#21]
Hello,

this package is really great but I noticed something, that's ruining the experience : 

There seems to be no option / key binding to unfold only the current level. In other words, when you use "fold-here" on a branch, it also unfolds all the sub-levels. Is there any workaround to this or are you planning on overhauling this? I'd very much appreciate that.

Greetings
Nils

**Comment by bsegraves** [comment]
Unfortunately this is a problem inherent with the API that Atom provides. I'm simply calling "Unfold row". The sub-folds are being automatically unfolded at the same time by Atom.

The only "solution" I can think of is to store all the folds locally and re-apply the internal folds after unfolding the outer layer. Definitely a hack but it's the only solution I can think of given the current API.

**Comment by DavidS3141** [comment]
I would also find this feature very useful. Are you working on this or going to in the near future? Otherwise I might have a look at it when I have time (which is probably not before September).

Except this minor issue your package is great, should be more popular! Thanks!

**Comment by bsegraves** [comment]
Too much going on at work to try and tackle this - I doubt I'll have anytime to look into this in the near future.

**Comment by AionDev** [comment]
yep, same here. I'm in a pretty big project and i spend a ton of time unfolding back the sub trees. Pain in the ass 😢 . I try to keep stuff unfolded which is less painful but still ...
Rely great package despite this flaw 😄

**Comment by bsegraves** [comment]
This appears to work in atom 1.25 beta 2. In other words, the state of inner fold regions are preserved when folding/unfolding outer fold regions.

This was a bug in the folding api provided by atom and they finally fixed it.
