### ISSUE TITLE
Deprecated selector in `custom-folds/styles/custom-folds.less`

### ISSUE THREAD

**Issue by victoriafrench** [bsegraves/custom-folds#23]
In `custom-folds/styles/custom-folds.less`:

Starting from Atom v1.13.0, the contents of `atom-text-editor` elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using `:host` and `::shadow` pseudo-selectors, and prepend all your syntax selectors with `syntax--`. To prevent breakage with existing style sheets, Atom will automatically upgrade the following selectors:

* `atom-text-editor::shadow .custom-folds-start:not(.no-highlight) .source .comment.block, atom-text-editor::shadow .custom-folds-start:not(.no-highlight) .text .comment.block, atom-text-editor::shadow .custom-folds-start:not(.no-highlight) .source .comment.definition, atom-text-editor::shadow .custom-folds-start:not(.no-highlight) .text .comment.definition, atom-text-editor::shadow .custom-folds-start:not(.no-highlight) .source .comment.line, atom-text-editor::shadow .custom-folds-start:not(.no-highlight) .text .comment.line` => `atom-text-editor.editor .custom-folds-start:not(.no-highlight) .syntax--source .syntax--comment.syntax--block, atom-text-editor.editor .custom-folds-start:not(.no-highlight) .syntax--text .syntax--comment.syntax--block, atom-text-editor.editor .custom-folds-start:not(.no-highlight) .syntax--source .syntax--comment.syntax--definition, atom-text-editor.editor .custom-folds-start:not(.no-highlight) .syntax--text .syntax--comment.syntax--definition, atom-text-editor.editor .custom-folds-start:not(.no-highlight) .syntax--source .syntax--comment.line, atom-text-editor.editor .custom-folds-start:not(.no-highlight) .syntax--text .syntax--comment.line`

* `atom-text-editor::shadow .custom-folds-start:not(.no-highlight) .source .comment.block .leading-whitespace, atom-text-editor::shadow .custom-folds-start:not(.no-highlight) .text .comment.block .leading-whitespace, atom-text-editor::shadow .custom-folds-start:not(.no-highlight) .source .comment.definition .leading-whitespace, atom-text-editor::shadow .custom-folds-start:not(.no-highlight) .text .comment.definition .leading-whitespace, atom-text-editor::shadow .custom-folds-start:not(.no-highlight) .source .comment.line .leading-whitespace, atom-text-editor::shadow .custom-folds-start:not(.no-highlight) .text .comment.line .leading-whitespace` => `atom-text-editor.editor .custom-folds-start:not(.no-highlight) .syntax--source .syntax--comment.syntax--block .leading-whitespace, atom-text-editor.editor .custom-folds-start:not(.no-highlight) .syntax--text .syntax--comment.syntax--block .leading-whitespace, atom-text-editor.editor .custom-folds-start:not(.no-highlight) .syntax--source .syntax--comment.syntax--definition .leading-whitespace, atom-text-editor.editor .custom-folds-start:not(.no-highlight) .syntax--text .syntax--comment.syntax--definition .leading-whitespace, atom-text-editor.editor .custom-folds-start:not(.no-highlight) .syntax--source .syntax--comment.line .leading-whitespace, atom-text-editor.editor .custom-folds-start:not(.no-highlight) .syntax--text .syntax--comment.line .leading-whitespace`

* `atom-text-editor::shadow .custom-folds-start:not(.no-highlight) .text.plain => atom-text-editor.editor .custom-folds-start:not(.no-highlight) .syntax--text.syntax--plain
atom-text-editor::shadow .custom-folds-start:not(.no-highlight) .text.plain.leading-whitespace, atom-text-editor::shadow .custom-folds-start:not(.no-highlight) .text.plain .leading-whitespace` => `atom-text-editor.editor .custom-folds-start:not(.no-highlight) .syntax--text.syntax--plain.leading-whitespace, atom-text-editor.editor .custom-folds-start:not(.no-highlight) .syntax--text.syntax--plain .leading-whitespace`

* `atom-text-editor::shadow .custom-folds-stop:not(.no-highlight) .source .comment.block, atom-text-editor::shadow .custom-folds-stop:not(.no-highlight) .text .comment.block, atom-text-editor::shadow .custom-folds-stop:not(.no-highlight) .source .comment.definition, atom-text-editor::shadow .custom-folds-stop:not(.no-highlight) .text .comment.definition, atom-text-editor::shadow .custom-folds-stop:not(.no-highlight) .source .comment.line, atom-text-editor::shadow .custom-folds-stop:not(.no-highlight) .text .comment.line` => `atom-text-editor.editor .custom-folds-stop:not(.no-highlight) .syntax--source .syntax--comment.syntax--block, atom-text-editor.editor .custom-folds-stop:not(.no-highlight) .syntax--text .syntax--comment.syntax--block, atom-text-editor.editor .custom-folds-stop:not(.no-highlight) .syntax--source .syntax--comment.syntax--definition, atom-text-editor.editor .custom-folds-stop:not(.no-highlight) .syntax--text .syntax--comment.syntax--definition, atom-text-editor.editor .custom-folds-stop:not(.no-highlight) .syntax--source .syntax--comment.line, atom-text-editor.editor .custom-folds-stop:not(.no-highlight) .syntax--text .syntax--comment.line`

* `atom-text-editor::shadow .custom-folds-stop:not(.no-highlight) .source .comment.block .leading-whitespace, atom-text-editor::shadow .custom-folds-stop:not(.no-highlight) .text .comment.block .leading-whitespace, atom-text-editor::shadow .custom-folds-stop:not(.no-highlight) .source .comment.definition .leading-whitespace, atom-text-editor::shadow .custom-folds-stop:not(.no-highlight) .text .comment.definition .leading-whitespace, atom-text-editor::shadow .custom-folds-stop:not(.no-highlight) .source .comment.line .leading-whitespace, atom-text-editor::shadow .custom-folds-stop:not(.no-highlight) .text .comment.line .leading-whitespace` => `atom-text-editor.editor .custom-folds-stop:not(.no-highlight) .syntax--source .syntax--comment.syntax--block .leading-whitespace, atom-text-editor.editor .custom-folds-stop:not(.no-highlight) .syntax--text .syntax--comment.syntax--block .leading-whitespace, atom-text-editor.editor .custom-folds-stop:not(.no-highlight) .syntax--source .syntax--comment.syntax--definition .leading-whitespace, atom-text-editor.editor .custom-folds-stop:not(.no-highlight) .syntax--text .syntax--comment.syntax--definition .leading-whitespace, atom-text-editor.editor .custom-folds-stop:not(.no-highlight) .syntax--source .syntax--comment.line .leading-whitespace, atom-text-editor.editor .custom-folds-stop:not(.no-highlight) .syntax--text .syntax--comment.line .leading-whitespace`

* `atom-text-editor::shadow .custom-folds-stop:not(.no-highlight) .text.plain => atom-text-editor.editor .custom-folds-stop:not(.no-highlight) .syntax--text.syntax--plain
atom-text-editor::shadow .custom-folds-stop:not(.no-highlight) .text.plain.leading-whitespace, atom-text-editor::shadow .custom-folds-stop:not(.no-highlight) .text.plain .leading-whitespace` => `atom-text-editor.editor .custom-folds-stop:not(.no-highlight) .syntax--text.syntax--plain.leading-whitespace, atom-text-editor.editor .custom-folds-stop:not(.no-highlight) .syntax--text.syntax--plain .leading-whitespace`

* `atom-text-editor::shadow .gutter:hover .line-number.custom-folds-start .icon-right` => `atom-text-editor.editor .gutter:hover .line-number.custom-folds-start .icon-right`

* `atom-text-editor::shadow .gutter:hover .line-number.custom-folds-start .icon-right:hover` => `atom-text-editor.editor .gutter:hover .line-number.custom-folds-start .icon-right:hover`

Automatic translation of selectors will be removed in a few release cycles to minimize startup time. Please, make sure to upgrade the above selectors as soon as possible.

**Comment by bsegraves** [comment]
Just released version 1.9.3 that fixes this. Thanks for the report!

**Comment by bsegraves** [comment]
Sorry, I meant 1.9.2.
