### ISSUE TITLE
Atom detected deprecated call: TextEditor.get

### ISSUE THREAD

**Issue by rgsilva** [bsegraves/custom-folds#25]
Hi!

This is from the automatic deprecated call detection. Got it on Atom 1.13.0 x64 and custom-folds 1.9.3.

**TextEditor.get is deprecated**

`TextEditor.prototype.displayBuffer` has always been private, but now it is gone. Reading the `displayBuffer` property now returns a reference to the containing `TextEditor`, which now provides *some* of the API of the defunct `DisplayBuffer` class.
```
TextEditor.get (/opt/atom/resources/app.asar/src/text-editor.js:101:14)
<unknown> (/home/ricardo/.atom/packages/custom-folds/lib/index.js:217:21)
Function.module.exports.Emitter.simpleDispatch (/opt/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
Emitter.emit (/opt/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
<unknown> (/opt/atom/resources/app.asar/src/workspace.js:265:34)
Function.module.exports.Emitter.simpleDispatch (/opt/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
```

**Comment by bsegraves** [comment]
Finally figured out how to repro. Fixed in 1.9.4.
