### ISSUE TITLE
Language specific comment settings

### ISSUE THREAD

**Issue by TravisJoe** [bsegraves/custom-folds#3]
I use several languages and love the idea of folding section of my code in each language. But only having one section start/stop style limits this.

**Comment by thtliife** [comment]
I have submitted a pull request which addresses this by removing the need for specifying comments, and only needing the region tag specified... as long as Atom understands the comment characters for the language you are writing, you can just use a commented version of your tag.
eg: 
start comment: `<editor-region>`
end comment: `</editor-region>`
This will work for:
```
// <editor-region>
  ...
// </editor-region>
```
or 
```
<!--<editor-region>
  ...
</editor-region>-->
```
or
```
#<editor-region>
  ...
#</editor-region>
```
etc...

**Comment by TravisJoe** [comment]
That is awesome! 

Thanks for the time and effort.

**Comment by bsegraves** [comment]
This PR has been merged and should be available if you go into settings in Atom and update your packages.

Next up is adding the ability to define multiple pairs of region tags, so you can vary the tag per language if you wish.

**Comment by vjpr** [comment]
This doesn't seem to work when there is not whitespace after the comment chars:

```
#region Foo
...
#endregion
```

**Comment by bsegraves** [comment]
Odd. The code appears to allow for that. I'll have to debug to figure out why. Been swamped at work lately but will try and take a look soon.

**Comment by nheath** [comment]
yeah, seeing the same thing. using c# style regions (to accommodate other devs)

these don't work
```
//#region Injection
//#endregion
```

but these do
```
// #region Injection
// #endregion
```

**Comment by bsegraves** [comment]
I just pushed version 1.6.7 that fixes this.

Atom, through its libraries, exposes the prefix that identifies comments but apparently doesn't trim it. I'm sure they have their reasons, but for our purposes we need it trimmed. 1.6.7 now trims this, so "//#region" should now work with 1.6.7 of this plugin.

**Comment by nheath** [comment]
👍  thx. works for me :)
