### ISSUE TITLE
problem with unfolding and default folding structure

### ISSUE THREAD

**Issue by babakzarrinbal** [bsegraves/custom-folds#31]
hey there 
really nice package ...
when unfolding custom folds it also unfolds all of its sub categories :( that's not cool 
and also when folding all with alt-ctrl-shift-[ it does not apply to custom folds 
maybe I'm doing something wrong . please enlighten me if that's the case

**Comment by bsegraves** [comment]
This appears to work as expected in atom 1.25 beta 2.

This was a bug in the folding api provided by atom and they finally fixed it.

**Comment by babakzarrinbal** [comment]
tnx 
keep up the good job
