### ISSUE TITLE
Mouse up when opening a custom fold closes it again

### ISSUE THREAD

**Issue by ColinT** [bsegraves/custom-folds#32]
When opening a custom fold, the fold opens on mouse down. If the cursor is not moved, the fold closes again on mouse up. Dragging the cursor to a different location before mouse up does not cause this behaviour.

Steps to reproduce:
- Make a custom fold section
- Close the fold
- Open the fold by clicking, without moving the cursor between mouse down and mouse up

Occurs on atom v1.19.0
bsegraves/custom-folds v1.9.4

**Comment by bsegraves** [comment]
Thanks for the report. This is new behavior, presumably started with atom 1.19. It looks like atom is handling the event before we get informed of it. Not entirely sure how to work around this yet.

**Comment by MaximeDawn** [comment]
Same issue here, just to mention, because none of you did it, if you just drag a little the mouse beetween mouse down and mouse up, the problem does not occur. 😉

**Comment by eskemojoe007** [comment]
Also, clicking the small ... icon to the right of text works, but I am experiencing the same behavior.

**Comment by bsegraves** [comment]
Sorry this took so long to fix. I've been slammed at work.

Version 1.9.5 is up and fixes this.

Let me know if you encounter any problems.
