### ISSUE TITLE
toggle does not work

### ISSUE THREAD

**Issue by mvdmolen** [bsegraves/custom-folds#5]
I can ctrl-shift-[ and ctrl-shift-] to open and close a region.

But I can't use ctrl-shift-\ to toggle that same region.

Also, the documentation says to use ctrl-alt-\ for toggle, but that doesn't work either.

**Comment by bsegraves** [comment]
Oops. The README.md was wrong. I updated it to be ctrl-shift-\ for toggling a region and pushed a new version.

But you report that ctrl-shift-\ isn't working for you? Is it possible another plugin grabbed that shortcut?

If you go to Packages\custom-folds in the menu bar, does it show ctrl-shift-\ for "Toggle Fold"?

**Comment by bsegraves** [comment]
Having heard any feedback, so closing this for now. Feel free to reopen if you're still experiencing issues.
