### ISSUE TITLE
Keybind clash with Atom's Fold All

### ISSUE THREAD

**Issue by AndrewTHowell** [bsegraves/custom-folds#52]
The keybindings 'Fold All' and 'Unfold All' clash with Atom's built-in folding functions. I'm very new to Atom, shouldn't the package overwrite default keybindings?

If not, how do I overwrite the keybindings to use this package's Fold/Unfold All commands?

Apologies if this is a stupid, easily solvable question,

**Comment by bsegraves** [comment]
If you go to Atom's preferences, select Packages, then click on Settings for the custom-folds package, you can modify the key bindings for this package.
