### ISSUE TITLE
[Feaure request] Fold buttons on the left bar

### ISSUE THREAD

**Issue by joan** [bsegraves/custom-folds#7]
A `›` button in the left line-numbers bar should be welcome to easily fold groups.

(Oh and, any way to disable that blue / underline style on foldable lines?)

Thanks!

**Comment by bsegraves** [comment]
Definitely agree on the icon in the left margin. Work has been a bit hectic lately - hopefully if time opens up I can take a look at that.

As far as disabling the blue underline, you can easily do this from the settings. From within Atom, just go to "Settings / Packages / custom-folds / Settings" and uncheck "Enable region highlighting".

**Comment by joan** [comment]
Great news to here, thanks!
Thanks for the tip, I missed that setting on the first look.

**Comment by 0tho** [comment]
https://github.com/bsegraves/custom-folds/pull/9

**Comment by bsegraves** [comment]
Merged. Version 1.7.0 pushed. Thanks!
